INSERT INTO tt_inspect
(creator,
 devicecode,
 creationtime,
 spec,
 wirenum,
 wiretype,
 breakspec,
 twbatchcode,
 trbatchcode,
 dlwarehouse,
 tgproducttime,
 breakflag,
 breakpointa,
 breakpointb,
 memo,
 devicecategory,
 breakreasona,
 billflag,
 id)
    VALUE (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?)